### ISSUE TITLE
Bug with multiplied siblings

### ISSUE THREAD

**Issue by graeme-hill** [pa-bru/graphql-cost-analysis#14]
I think the cost calculated for nested siblings is treating the second sibling like it is a child. Here is a repro:

```graphql
type Query {
  things (limit: Int = 50): [Thing!]! @cost(multipliers: ["limit"], complexity: 1)
}

type Thing {
  name: String!
  subThingsA (limit: Int = 50): [SubThing!]! @cost(multipliers: ["limit"], complexity: 1)
  subThingsB (limit: Int = 50): [SubThing!]! @cost(multipliers: ["limit"], complexity: 1)
}

type SubThing {
  name: String!
}
```

Sample query:

```graphql
query {
  things {
    subThingsA
    subThingsB
  }
}
```

Expected cost: 5050 `(1 * 50) + (1 * 50 * 50) + (1 * 50 * 50)`
Actual cost: 127550 `(1 * 50) + (1 * 50 * 50) + (1 * 50 * 50 * 50)`

**Comment by mxstbr** [comment]
Yeah also running into this

**Comment by pa-bru** [comment]
Yes I understand the issue. this is because we systematically add each new multiplier to the `operationMultiplier` list so it doesn't care about siblings. 

A solution could be to create a multipliers list for each query part. 
e.g: a list for `things. subThingsA` and another for `things. subThingsB`.

Another solution could be to use the GraphQL schema.

**Update**: @graeme-hill, @mxstbr,  I'm working on a quick fix that will be merged soon and added in the next patch release of the npm package
